server.port=8081
user.service.message=User Service is running from Config Server
spring.application.name=USER-SERVICE

management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans

spring.datasource.username=root
spring.datasource.password={cipher}7a68837784623d897aaf0f2d91014b273c4affd17eae66a0f27f2b4eec62db61
